server:
  port: 5050
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:15432/mydb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: multi-tenant-pool
  sql:
    init:
      # 執行 schema.sql 的超級權限帳號，可以執行 POLICY 並且建立一個一般使用者
      username: root
      password: password
      mode: always
      platform: schema_per_tenant
      encoding: UTF-8
      continue-on-error: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        multiTenancy: NONE # DISCRIMINATOR = Share Schema、SCHEMA = Schema-per-tenant、DATABASE = DB-per-tenant
        type:
          json_format_mapper: com.demo.config.CustomHibernateJsonFormatter
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%-4t] %-40.40logger{39} : %m%n'