spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: false # 若有 SQL 失敗是否繼續啟動伺服器
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # 順序上與 JDBC 機制不順，所以建議設定 none、validate
